### `Task` Train a Lasso And Ridge Regression model on Boston House Price Datset. And also show how it reduces overfitting in compare to normal Linear regression model.

Data set Link - https://www.kaggle.com/datasets/altavish/boston-housing-dataset

DataSet description:
```
ZN: proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS: proportion of non-retail business acres per town
CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
NOX: nitric oxides concentration (parts per 10 million)
RM: average number of rooms per dwelling
AGE: proportion of owner-occupied units built prior to 1940
DIS: weighted distances to ﬁve Boston employment centers
RAD: index of accessibility to radial highways
TAX: full-value property-tax rate per $10,000
PTRATIO: pupil-teacher ratio by town 12. B: 1000(Bk−0.63)2 where Bk is the proportion of blacks by town 13. LSTAT: % lower status of the population
MEDV: Median value of owner-occupied homes in $1000s (Target)
```

In [92]:
# Your Code goes here
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import kagglehub
path = kagglehub.dataset_download("altavish/boston-housing-dataset")

Using Colab cache for faster access to the 'boston-housing-dataset' dataset.

In [93]:
import os
files = os.listdir(path)

csv_files = [f for f in files if f.endswith(".csv")]

df = pd.read_csv(os.path.join(path, csv_files[0]))

df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [94]:
df.shape

(506, 14)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [96]:
null_cols = df.isna().sum()[df.isna().sum()>0].index
df.isna().sum()
for x in null_cols:
  df[x] = df[x].fillna(df[x].median())

In [97]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

X = df.drop(columns=['MEDV'])
y = df['MEDV']

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [98]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)
print("R2 Score of LR",r2_score(y_test,y_pred_lr))

rr = Ridge()
rr.fit(X_train,y_train)
y_pred_rr = rr.predict(X_test)
print("R2 Score of RR",r2_score(y_test,y_pred_rr))

lsr = Lasso()
lsr.fit(X_train,y_train)
y_pred_lsr = lsr.predict(X_test)
print("R2 Score of RR",r2_score(y_test,y_pred_lsr))

R2 Score of LR 0.6591013893903506
R2 Score of RR 0.6563634005704594
R2 Score of RR 0.6714087654911365

In [99]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_squared_error
import pandas as pd

models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=10),
    "Lasso Regression": Lasso(alpha=0.001, max_iter=10000)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Train R²": r2_score(y_train, y_train_pred),
        "Test R²": r2_score(y_test, y_test_pred),
        "Train MSE": mean_squared_error(y_train, y_train_pred),
        "Test MSE": mean_squared_error(y_test, y_test_pred)
    })

results_df = pd.DataFrame(results)
print(results_df.round(4))

               Model  Train R²  Test R²  Train MSE  Test MSE
0  Linear Regression    0.7426   0.6591    22.3631   24.9994
1   Ridge Regression    0.7341   0.6559    23.1006   25.2371
2   Lasso Regression    0.7426   0.6591    22.3635   24.9989

In [102]:
from sklearn.metrics import r2_score, mean_squared_error
from mlxtend.evaluate import bias_variance_decomp

lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)
print("R2 Score of LR",r2_score(y_test,y_pred_lr))
print("MSE",(mean_squared_error(y_test,y_pred_lr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        lr, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)


print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

print("="*50)

rr = Ridge(alpha=100000)
rr.fit(X_train,y_train)
y_pred_rr = rr.predict(X_test)
print("\nR2 Score of RR",r2_score(y_test,y_pred_rr))
print("MSE",(mean_squared_error(y_test,y_pred_rr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        rr, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)
print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

print("="*50)



lsr = Lasso(alpha=100000)
lsr.fit(X_train,y_train)
y_pred_lsr = lsr.predict(X_test)
print("\nR2 Score of RR",r2_score(y_test,y_pred_lsr))
print("MSE",(mean_squared_error(y_test,y_pred_lsr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        lsr, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)

print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

R2 Score of LR 0.6591013893903506
MSE 24.999384790103406

Average expected loss: 26.257
Average bias: 25.251
Average variance: 1.006
==================================================

R2 Score of RR 0.4088778178378596
MSE 43.349225927935336

Average expected loss: 43.803
Average bias: 43.338
Average variance: 0.465
==================================================

R2 Score of RR -0.023340500652033302
MSE 75.04543037399255

Average expected loss: 75.278
Average bias: 75.057
Average variance: 0.221

- `avg_expected_loss` is an estimate of test/generalization MSE, not training MSE.

### `Task` perform Lasso and Ridge in Wine Quality dataset and show how it's different from Linear Regression.

Data link : https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv

In [103]:
# Loading Wine dataset
import pandas as pd
wine_data_path = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv"
df = pd.read_csv(wine_data_path)

In [104]:
# Your Code goes here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [105]:
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [106]:
print("Total Null Values",df.isnull().sum().sum())
display(df['type'].value_counts())

Total Null Values 38

type
white    4898
red      1599
Name: count, dtype: int64

In [107]:
null_value_cols = df.isnull().sum()[df.isnull().sum()>0].index.tolist()

In [116]:
null_value_cols

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'pH',
 'sulphates']

In [108]:
# Null value dtype
df[null_value_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fixed acidity     6487 non-null   float64
 1   volatile acidity  6489 non-null   float64
 2   citric acid       6494 non-null   float64
 3   residual sugar    6495 non-null   float64
 4   chlorides         6495 non-null   float64
 5   pH                6488 non-null   float64
 6   sulphates         6493 non-null   float64
dtypes: float64(7)
memory usage: 355.4 KB

In [109]:
# Encode the categorical column
df = pd.get_dummies(df,columns=['type'],drop_first=True,dtype=int)

In [117]:
df[null_value_cols] = df[null_value_cols].fillna(df[null_value_cols].median())

In [118]:
X = df.drop(columns=['quality'])
y = df['quality']

In [122]:
from sklearn.pipeline import Pipeline
lr_pipeline = Pipeline([
    ('model',LinearRegression())
])

lr_pipeline.fit(X_train,y_train)
y_pred_lr = lr_pipeline.predict(X_test)


rr_pipeline = Pipeline([
    ('model',Ridge(alpha=1000))
])

rr_pipeline.fit(X_train,y_train)
y_pred_rr = rr_pipeline.predict(X_test)


lsr_pipeline = Pipeline([
    ('model',Lasso(alpha=1000))
])
lsr_pipeline.fit(X_train,y_train)
y_pred_lsr = lsr_pipeline.predict(X_test)

In [123]:
from sklearn.metrics import r2_score, mean_squared_error
from mlxtend.evaluate import bias_variance_decomp


print("R2 Score of LR",r2_score(y_test,y_pred_lr))
print("MSE",(mean_squared_error(y_test,y_pred_lr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        lr_pipeline, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)


print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

print("="*50)


print("\nR2 Score of RR",r2_score(y_test,y_pred_rr))
print("MSE",(mean_squared_error(y_test,y_pred_rr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        rr_pipeline, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)
print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

print("="*50)




print("\nR2 Score of RR",r2_score(y_test,y_pred_lsr))
print("MSE",(mean_squared_error(y_test,y_pred_lsr)))

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        lsr_pipeline, X_train.values, y_train.values, X_test.values, y_test.values,
        loss='mse',
        random_seed=42)

print('\nAverage expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

R2 Score of LR 0.34080652030478464
MSE 0.4711911092308265

Average expected loss: 0.473
Average bias: 0.471
Average variance: 0.002
==================================================

R2 Score of RR 0.2697459792496104
MSE 0.5219851419294076

Average expected loss: 0.523
Average bias: 0.522
Average variance: 0.001
==================================================

R2 Score of RR -1.2504991929951359e-05
MSE 0.7148083468448557

Average expected loss: 0.715
Average bias: 0.715
Average variance: 0.000